### ISSUE TITLE
What do we need for launch?

### ISSUE THREAD

**Issue by edwardloveall** [jneen/rouge.jneen.net#11]
I think we've accomplished a lot of the goals we've set out to do so far. There are a couple things I know are left:

- [ ] Some kind of analytics service integration, be it Google Analytics or something else (especially if we ant to A/B test)
- [x] Style edits that @jneen mentioned in #10 

Is there anything else that I'm forgetting?

**Comment by jneen** [comment]
Sounds good!  I'm willing the postpone analytics if need be, and for the style edits I think we just need to make it a bit less pastel still.  Other than that we're good to go, yeah.

**Comment by jneen** [comment]
Thanks for everything you've done by the way this is fantastic

**Comment by edwardloveall** [comment]
Ok I'll make a pass on it that's a little less Valentines. And you're welcome! Thanks for the opportunity and freedom. I'm really proud of the site.

**Comment by jneen** [comment]
yaaay :)

**Comment by jneen** [comment]
I'm having trouble getting this going on heroku - it seems some environment variables are missing.  Is there anything different than the vanilla heroku setup that's needed?

**Comment by edwardloveall** [comment]
Possibly environment variables. Should just be `HASHIDS_SALT`:

```
heroku config:set HASHIDS_SALT=foo
```

But set `foo` to a good salt value.

**Comment by jneen** [comment]
Hrm, okay, now it's serving 500s and there's no error in the logs... I'm not that familiar with heroku, is there something I'm missing?

**Comment by edwardloveall** [comment]
Can you give me access to it? My heroku account is the same email you have.

**Comment by edwardloveall** [comment]
Any luck with this

**Comment by jneen** [comment]
Pretty sure I added you?

**Comment by jneen** [comment]
well dang, must not have gone through. you should be there now.

**Comment by edwardloveall** [comment]
Cool should be up now. The database wasn't set up or migrated. I'll give you access to my staging site so we can test deploy's in the future.

**Comment by jneen** [comment]
well dang, must not have gone through. you should be there now.
