### ISSUE TITLE
I literally can't figure out how to work heroku anymore, can I just run this on my server

### ISSUE THREAD

**Issue by jneen** [jneen/rouge.jneen.net#26]
I think it'll be a lot easier for me to keep this up to date if I just run it on my server - the same one that serves the root jneen.net and tuliplang.org.

**Comment by edwardloveall** [comment]
sure, if you want to. Having spun up my own servers I find that quite a bit more difficult, but if you want to take on the work: 👍 

I'll make a PR this weekend that updates rouge and strips out heroku stuff if there is any. Then you can make one for any custom server stuff you want.

**Comment by edwardloveall** [comment]
Or, I can deal with the heroku stuff if you'd rather. There's a lot we could do with automatic deploys and CI that I just set up today for a different app so I'm in the headspace for it. Up to you.

**Comment by jneen** [comment]
If we can set up automatic deploys I think heroku is still fine. I'm locked out of my heroku account, so I can't do much at all.

**Comment by jneen** [comment]
It's just not sustainable for me to have to reinstall the entire heroku toolchain and get support to unlock my account for every deploy.

**Comment by jneen** [comment]
...where if it were on a server I actually controlled I'd just use my ssh key...

**Comment by jneen** [comment]
Okayyy I've got heroku working again

**Comment by jneen** [comment]
So I'm just going to deploy for now, but in general I think it'd be better if an automated thing ran this - maybe even hooked into rouge releases :]

**Comment by edwardloveall** [comment]
Cool, I'll try to set that up this weekend. I'll ping you (somehow) if I need special access.
