### ISSUE TITLE
Colouring in Pale Moon

### ISSUE THREAD

**Issue by sergeevabc** [jneen/rouge.jneen.net#34]
[Pale Moon][2] 27.6 (a fork of Firefox ESR 38) x64.

Put cursor into selectbox with colour schemes on Rouge’s [demo website][1] and press UP or DOWN.
Colouring in the right box should change appropriately, but it does not happen.
Could you be so kind to fix it?

[1]: http://rouge.jneen.net/
[2]: http://www.palemoon.org/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by edwardloveall** [comment]
Hi @sergeevabc. Sorry about not responding sooner. I looked into this and ran into some roadblocks. First, I tried on the latest downloadable Firefox and everything worked as expected there. I was going to look at the browser you're using but it's only for windows and I only have access to macOS.

Is this bug causing a problem for you? Are you unable to use the site?

**Comment by sergeevabc** [comment]
@edwardloveall, please, watch [screencast][1] about bug and try [unofficial build][1] of Pale Moon for macOS.

[1]: https://sub.god.jp/f/k4m1lBmf.mp4
[2]: https://forum.palemoon.org/viewtopic.php?f=41&t=17420

**Comment by edwardloveall** [comment]
@sergeevabc thanks for the video and letting me know there's a macOS build. I tried it out on my machine and it's showing the same behavior. I'm going to mark this `wontfix` for two reasons.

First, I don't expect people to switch quickly through languages. It's an interesting curiosity to see how the same text is rendered in language X, then Y, then Z, but it's not what @jneen and I built that page for.

Second, Pale Moon seems to be the only browser that has this behavior. Although it's not explicitly stated, I'm only testing in the more major browsers (Firefox, Chrome, Safari, Edge).

Sorry, I know this is disappointing. If this starts becoming an issue in those browsers, and I see that a lot of people want to switch through the language like that then we can readdress it then.

**Comment by edwardloveall** [comment]
It's a good thought, but I checked out that branch locally, and tried Palemoon but it was the same. It seems that Palemoon is not sending a the javascript `change` event when it is changed with the arrow keys. I did notice that if I hit Enter, it would detect the change and switch the language. Maybe that would work for you. 🙂
